image: node:11.11

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

ğŸ§ªtests:
  stage: test
  script:
    - npm install
    - npm test

â¯deploy-chrome:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq zip
  script:
    - npm install
    - npm run chromeRelease
  only:
    - tags
