image: node:11.11

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

ğŸ§ªtests:
  stage: test
  script:
    - npm test

â¯deploy-chrome:
  stage: deploy
  script:
    - npm chromeRelease
  only:
    - master

â¯deploy-chrome-beta:
  stage: deploy
  script:
    - npm chromeReleaseBeta
  except:
    - master